// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "gews_more/service/internal/handler/login"
	"gews_more/service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: login.LoginHandler(serverCtx),
			},
		},
	)
}
