// Code generated by goctl. DO NOT EDIT.
package types

type Reque struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Respo struct {
	Error_code int  `json:"error_code"`
	Data       Data `json:"data"`
}

type Data struct {
	Uid   int    `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Registercodereque struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Registercoderespo struct {
	Error_code int `json:"error_code"`
}

type Registerreque struct {
	Name     string `json:"name"`
	Emial    string `json:"email"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type Registerrespo struct {
	Error_code int          `json:"error_code"`
	Data       Registerdata `json:"data"`
}

type Registerdata struct {
	Uid   int    `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Snapreque struct {
	Name string `json:"name"`
}

type Snaprespo struct {
	Error_code int    `json:"error_code"`
	Snaps      []Snap `json:"snaps"`
}

type Snap struct {
	Sid     int    `json:"sid"`
	Speaker string `json:"speaker"`
	Message string `json:"message"`
	Date    string `json:"date"`
	At      string `json:"at"`
}

type Snappostreque struct {
	Speaker string `json:"speaker"`
	Message string `json:"message"`
	Date    string `json:"date"`
	At      string `json:"at"`
}

type Snappostrespo struct {
	Error_code int `json:"error_code"`
}

type Trendingreque struct {
	Name string `json:"name"`
}

type Trendingrespo struct {
	Error_code int        `json:"error_code"`
	Trending   []Trending `json:"trending"`
}

type Trending struct {
	Tid     int    `json:"tid"`
	Tittle  string `json:"title"`
	Img     string `json:"img"`
	Content string `json:"content"`
	Href    string `json:"href"`
}
