// Code generated by goctl. DO NOT EDIT.
package types

type Reque struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Respo struct {
	Error_code int  `json:"error_code"`
	Data       Data `json:"data"`
}

type Data struct {
	Uid   int    `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Registercodereque struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Registercoderespo struct {
	Error_code int      `json:"error_code"`
	Data       CodeData `json:"data"`
}

type CodeData struct {
	Code string `json:"code"`
}

type Registerreque struct {
	Name     string `json:"name"`
	Emial    string `json:"email"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type Registerrespo struct {
	Error_code int          `json:"error_code"`
	Data       Registerdata `json:"data"`
}

type Registerdata struct {
	Uid   int    `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
