// Code generated by goctl. DO NOT EDIT.
package types

type Reque struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type Respo struct {
	Error_code int  `json:"error_code"`
	Data       Data `json:"data"`
}

type Data struct {
	Uid   int    `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
